# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\post.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PostEdit(object):
    def setupUi(self, PostEdit):
        PostEdit.setObjectName("PostEdit")
        PostEdit.resize(560, 463)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PostEdit.sizePolicy().hasHeightForWidth())
        PostEdit.setSizePolicy(sizePolicy)
        PostEdit.setMinimumSize(QtCore.QSize(560, 0))
        PostEdit.setStyleSheet("*{\n"
"border-radius: 10px;\n"
"border: 1px solid #555;\n"
"background-color: rgb(14, 15, 18);\n"
"}\n"
"#frame_09, #frame_99, #frame_88{\n"
"border: none;\n"
"}\n"
"\n"
"#title, #description {\n"
"    border-radius: 5px;\n"
"    color:rgba(255, 255, 255, 150);\n"
"    padding-bottom:4px;\n"
"    background-color: #2C2828;\n"
"}\n"
"\n"
"#horizontalFrame{\n"
"background-color: none;\n"
"border : none;\n"
"}\n"
"\n"
"#backBtn, #confirmBtn{    \n"
"border: 1px solid #555;\n"
"font-weight: bold;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(254, 44, 85, 100), stop:1 rgba(0, 0, 0, 255));\n"
"border-radius: 5px;\n"
"color: #fff;\n"
"}\n"
"\n"
"#deletePostBtn{\n"
"border: 1px solid #555;\n"
"font-weight: bold;\n"
"background-color: rgba(254, 44, 85, 100);\n"
"border-radius: 10px;\n"
"color: #fff;\n"
"\n"
"}\n"
"#backBtn::hover, #confirmBtn::hover{    \n"
"font-weight: bold;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(254, 44, 85, 150), stop:1 rgba(0, 0, 0, 255));\n"
"}\n"
"\n"
"#backBtn::pressed, #confirmBtn::pressed{    \n"
"font-weight: bold;\n"
"padding-left:5px;\n"
"padding-top:2px;\n"
"background-color: #2C2828;\n"
"}\n"
"\n"
"\n"
"#deletePostBtn:hover{\n"
"font-weight: bold;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(254, 44, 85, 150), stop:1 rgba(0, 0, 0, 255));\n"
"\n"
"}\n"
"#deletePostBtn:pressed{\n"
"border: 1px solid #555;\n"
"padding-left:6px;\n"
"padding-top:4px;\n"
"        border-radius: 8px;\n"
"\n"
"    background-color: #2C2828;\n"
"}\n"
"")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(PostEdit)
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_09 = QtWidgets.QWidget(PostEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_09.sizePolicy().hasHeightForWidth())
        self.widget_09.setSizePolicy(sizePolicy)
        self.widget_09.setMinimumSize(QtCore.QSize(525, 0))
        self.widget_09.setObjectName("widget_09")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_09)
        self.horizontalLayout.setContentsMargins(6, -1, 1, -1)
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_88 = QtWidgets.QFrame(self.widget_09)
        self.frame_88.setMinimumSize(QtCore.QSize(226, 0))
        self.frame_88.setMaximumSize(QtCore.QSize(226, 16777215))
        self.frame_88.setObjectName("frame_88")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_88)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.thumbnailLabel = QtWidgets.QLabel(self.frame_88)
        self.thumbnailLabel.setMinimumSize(QtCore.QSize(212, 375))
        self.thumbnailLabel.setMaximumSize(QtCore.QSize(212, 375))
        self.thumbnailLabel.setStyleSheet("border-radius: 10px;")
        self.thumbnailLabel.setText("")
        self.thumbnailLabel.setPixmap(QtGui.QPixmap(":/images/images/thumbnail/DougSinglemann--CrowRiver2016.jpg"))
        self.thumbnailLabel.setScaledContents(True)
        self.thumbnailLabel.setObjectName("thumbnailLabel")
        self.verticalLayout_11.addWidget(self.thumbnailLabel)
        self.deletePostBtn = QtWidgets.QPushButton(self.frame_88)
        self.deletePostBtn.setMinimumSize(QtCore.QSize(212, 28))
        self.deletePostBtn.setMaximumSize(QtCore.QSize(212, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/icons/assets/icons/feather/x-octagon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deletePostBtn.setIcon(icon)
        self.deletePostBtn.setObjectName("deletePostBtn")
        self.verticalLayout_11.addWidget(self.deletePostBtn)
        self.horizontalLayout.addWidget(self.frame_88)
        self.frame_99 = QtWidgets.QFrame(self.widget_09)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_99.sizePolicy().hasHeightForWidth())
        self.frame_99.setSizePolicy(sizePolicy)
        self.frame_99.setMinimumSize(QtCore.QSize(280, 0))
        self.frame_99.setMaximumSize(QtCore.QSize(280, 16777215))
        self.frame_99.setObjectName("frame_99")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_99)
        self.verticalLayout_6.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.title = QtWidgets.QLineEdit(self.frame_99)
        self.title.setMinimumSize(QtCore.QSize(265, 22))
        self.title.setMaximumSize(QtCore.QSize(265, 22))
        self.title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.title.setObjectName("title")
        self.verticalLayout_6.addWidget(self.title)
        self.description = QtWidgets.QTextEdit(self.frame_99)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description.sizePolicy().hasHeightForWidth())
        self.description.setSizePolicy(sizePolicy)
        self.description.setMinimumSize(QtCore.QSize(265, 121))
        self.description.setMaximumSize(QtCore.QSize(265, 121))
        self.description.setObjectName("description")
        self.verticalLayout_6.addWidget(self.description)
        self.horizontalFrame = QtWidgets.QFrame(self.frame_99)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setMinimumSize(QtCore.QSize(271, 51))
        self.horizontalFrame.setMaximumSize(QtCore.QSize(271, 51))
        self.horizontalFrame.setStyleSheet("")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.backBtn = QtWidgets.QPushButton(self.horizontalFrame)
        self.backBtn.setMinimumSize(QtCore.QSize(100, 0))
        self.backBtn.setMaximumSize(QtCore.QSize(100, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/assets/icons/assets/icons/feather/arrow-left-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backBtn.setIcon(icon1)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout_16.addWidget(self.backBtn)
        self.confirmBtn = QtWidgets.QPushButton(self.horizontalFrame)
        self.confirmBtn.setMinimumSize(QtCore.QSize(100, 0))
        self.confirmBtn.setMaximumSize(QtCore.QSize(100, 16777215))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/assets/icons/assets/icons/feather/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.confirmBtn.setIcon(icon2)
        self.confirmBtn.setObjectName("confirmBtn")
        self.horizontalLayout_16.addWidget(self.confirmBtn)
        self.verticalLayout_6.addWidget(self.horizontalFrame)
        self.horizontalLayout.addWidget(self.frame_99)
        self.horizontalLayout_2.addWidget(self.widget_09)

        self.retranslateUi(PostEdit)
        QtCore.QMetaObject.connectSlotsByName(PostEdit)

    def retranslateUi(self, PostEdit):
        _translate = QtCore.QCoreApplication.translate
        PostEdit.setWindowTitle(_translate("PostEdit", "Form"))
        self.deletePostBtn.setText(_translate("PostEdit", "  D E L E T E   P O S T"))
        self.title.setText(_translate("PostEdit", "Title"))
        self.description.setHtml(_translate("PostEdit", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Description ...</span></p></body></html>"))
        self.backBtn.setText(_translate("PostEdit", "B A C K"))
        self.confirmBtn.setText(_translate("PostEdit", "S A V E"))
import resources_rc
