# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tikplayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoWidget(object):
    def setupUi(self, VideoWidget):
        VideoWidget.setObjectName("VideoWidget")
        VideoWidget.resize(212, 380)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VideoWidget.sizePolicy().hasHeightForWidth())
        VideoWidget.setSizePolicy(sizePolicy)
        VideoWidget.setMinimumSize(QtCore.QSize(212, 380))
        VideoWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(VideoWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(VideoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(212, 380))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setMouseTracking(True)
        self.label.setStyleSheet("background-color: transparent;")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.controlWidget = QtWidgets.QWidget(VideoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlWidget.sizePolicy().hasHeightForWidth())
        self.controlWidget.setSizePolicy(sizePolicy)
        self.controlWidget.setMinimumSize(QtCore.QSize(212, 20))
        self.controlWidget.setMaximumSize(QtCore.QSize(16777215, 20))
        self.controlWidget.setStyleSheet("background-color:  rgba(75, 75, 75, 200)")
        self.controlWidget.setObjectName("controlWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.controlWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playButton = QtWidgets.QToolButton(self.controlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setMaximumSize(QtCore.QSize(30, 20))
        self.playButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.playButton.setAutoFillBackground(False)
        self.playButton.setStyleSheet("background-color: transparent;")
        self.playButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/icons/assets/icons/feather/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon)
        self.playButton.setIconSize(QtCore.QSize(20, 20))
        self.playButton.setAutoRaise(True)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout.addWidget(self.playButton)
        self.QSlider = QtWidgets.QSlider(self.controlWidget)
        self.QSlider.setMinimumSize(QtCore.QSize(77, 13))
        self.QSlider.setMaximumSize(QtCore.QSize(16777215, 18))
        self.QSlider.setAutoFillBackground(False)
        self.QSlider.setStyleSheet("#QSlider::groove:horizontal{\n"
"border: 1px solid #FFFFFF;  background: #C0C0C0;  height: 1px;  border-radius: 1px;  padding-left:-1px;  padding-right:-1px;\n"
"}\n"
"\n"
"#QSlider::handle:horizontal{\n"
"background: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,   stop:0.6 #000, stop:0.778409 rgba(255, 255, 255, 255));  width: 11px;  margin-top: -5px;  margin-bottom: -5px;  border-radius: 5px;\n"
"}\n"
"*{\n"
"background-color: transparent;\n"
"margin-right: 1.5px;\n"
"}")
        self.QSlider.setMaximum(100)
        self.QSlider.setProperty("value", 0)
        self.QSlider.setOrientation(QtCore.Qt.Horizontal)
        self.QSlider.setObjectName("QSlider")
        self.horizontalLayout.addWidget(self.QSlider)
        self.timeLabel = QtWidgets.QLabel(self.controlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLabel.sizePolicy().hasHeightForWidth())
        self.timeLabel.setSizePolicy(sizePolicy)
        self.timeLabel.setMinimumSize(QtCore.QSize(76, 20))
        self.timeLabel.setMaximumSize(QtCore.QSize(76, 20))
        self.timeLabel.setStyleSheet("background-color: transparent; margin-left: 2px;")
        self.timeLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.timeLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.timeLabel.setScaledContents(True)
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setWordWrap(False)
        self.timeLabel.setIndent(0)
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout.addWidget(self.timeLabel, 0, QtCore.Qt.AlignHCenter)
        self.soundButton = QtWidgets.QToolButton(self.controlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.soundButton.sizePolicy().hasHeightForWidth())
        self.soundButton.setSizePolicy(sizePolicy)
        self.soundButton.setMinimumSize(QtCore.QSize(24, 20))
        self.soundButton.setMaximumSize(QtCore.QSize(27, 20))
        self.soundButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.soundButton.setStyleSheet("background-color: transparent;")
        self.soundButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/assets/icons/assets/icons/feather/volume-x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.soundButton.setIcon(icon1)
        self.soundButton.setIconSize(QtCore.QSize(20, 20))
        self.soundButton.setObjectName("soundButton")
        self.horizontalLayout.addWidget(self.soundButton)
        self.verticalLayout.addWidget(self.controlWidget)

        self.retranslateUi(VideoWidget)
        QtCore.QMetaObject.connectSlotsByName(VideoWidget)

    def retranslateUi(self, VideoWidget):
        _translate = QtCore.QCoreApplication.translate
        VideoWidget.setWindowTitle(_translate("VideoWidget", "Form"))
        self.timeLabel.setText(_translate("VideoWidget", "00:16/00:30"))
import resources_rc
